services:
  service:
    build: ./src
    expose:
      - 5000
    environment:
      - REDSI_HOST=redis
    volumes:
      - ./service/flag.txt:/flag.txt:ro
    depends_on:
      - redis
    networks:
      - ctf-net

  redis:
    image: redis:7-alpine
    networks:
      - ctf-net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8083:80"
    depends_on:
      - service
    networks:
      - ctf-net

networks:
  ctf-net:
    driver: bridge
